### ISSUE TITLE
请教一个报错

### ISSUE THREAD

**Issue by 12123ads** [yym68686/ChatGPT-Telegram-Bot#27]
![Screenshot_20240109_004228](https://github.com/yym68686/ChatGPT-Telegram-Bot/assets/69107029/d7bd04f4-1666-4e7c-b8d8-358a11cc48e9)

**Comment by yym68686** [comment]
我这边没有复现这个错误。把整个日志复制一下。看起来是请求体有问题。

**Comment by 12123ads** [comment]
我是使用docker&nbsp;compose运行的，这个具体的日志在哪里


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月9日(周二) 凌晨0:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yym68686/ChatGPT-Telegram-Bot] 请教一个报错 (Issue #27)




 
我这边没有复现这个错误。把整个日志复制一下。看起来是请求体有问题。
 
&mdash;

**Comment by yym68686** [comment]
> ![Screenshot_20240109_004228](https://private-user-images.githubusercontent.com/69107029/294972755-d7bd04f4-1666-4e7c-b8d8-358a11cc48e9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MzMwNTUsIm5iZiI6MTcwNDczMjc1NSwicGF0aCI6Ii82OTEwNzAyOS8yOTQ5NzI3NTUtZDdiZDA0ZjQtMTY2Ni00ZTdjLWI4ZDgtMzU4YTExY2M0OGU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDE2NTIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MGYxNGI1NTQ2YWJlMDQ5ZDZmMTBjNjU2MTZhODBiN2FjODgwNzQzODI3MjIyZjJjOWExMGMwZDM1NGE4OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zmUeRnm5QPeS3nL5UC8GbR496D73WV7snJ3UZEJFj40)

这个图上面所有的输出。

**Comment by 12123ads** [comment]
chatgptbot  | 2024-01-10 05:34:24,224 - telegram.ext.Application - INFO - Application started
chatgptbot  |  xzhnb 1308322356 你好
chatgptbot  | {'error': {'message': 'invalid paramters (request id: 20240110133442930502380EArpqarN)', 'type': 'invalid_request_error', 'param': '', 'code': None}}
chatgptbot  |
chatgptbot  | response_msg `🤖️ gpt-3.5-turbo`
chatgptbot  |
chatgptbot  |
chatgptbot  | error Unknown error
chatgptbot  | Traceback (most recent call last):
chatgptbot  |   File "/home/ChatGPT-Telegram-Bot/bot.py", line 132, in getChatGPT
chatgptbot  |     for data in get_answer(text, convo_id=str(chatid), pass_history=config.PASS_HISTORY):
chatgptbot  |   File "/home/ChatGPT-Telegram-Bot/utils/chatgpt2api.py", line 561, in ask_stream
chatgptbot  |     json_post, message_token = self.truncate_conversation(prompt, role, convo_id, model, pass_history, **kwargs)
chatgptbot  |   File "/home/ChatGPT-Telegram-Bot/utils/chatgpt2api.py", line 401, in truncate_conversation
chatgptbot  |     message_token = self.get_message_token(url, json_post)
chatgptbot  |   File "/home/ChatGPT-Telegram-Bot/utils/chatgpt2api.py", line 493, in get_message_token
chatgptbot  |     raise Exception("Unknown error")
chatgptbot  | Exception: Unknown error
chatgptbot  |
chatgptbot  | `🤖️ gpt-3.5-turbo`
chatgptbot  |
chatgptbot  | `出错啦！Unknown error`

**Comment by 12123ads** [comment]
version: "3"
services:
  chatgptbot:
    container_name: chatgptbot
    image: yym68686/chatgpt:1.0
    environment:
      - BOT_TOKEN=
      - API=sk-
      - API_URL=http://192.168.160.8:3000/v1
      - GPT_ENGINE=gpt-3.5-turbo
      - ADMIN_LIST=1308322356
      - WEB_HOOK=https://
    networks:
      chatgpt:
        ipv4_address: 192.168.160.17

networks:
  chatgpt:
    external: true

我使用的是one-api作为代理的站点

**Comment by yym68686** [comment]
我这边看不出来是什么问题。方便的话，你可以提供一下你的one-api url 和有限额度的api key给我使用gpt-3.5-turbo测试一下。

**Comment by yym68686** [comment]
看起来是one-api不支持传入某个参数。跟官方API实现有所区别。但具体是什么参数，还需要你提供一下测试API才能知道。

**Comment by 12123ads** [comment]
url: https://api.block.cf
sk-O2ik7vPdAVF5KMtTF75072A44dDd400b84C0D9B13e1aEeF5

**Comment by 12123ads** [comment]
这个接口是chat2api出来的，支持的不如原版api的多

**Comment by yym68686** [comment]
找到原因了。你这个API不支持gpt-4-vision-preview模型，gpt-4-vision-preview模型特有的API格式如下：

```
      {
          "role": "user",
          "content": [
              {
                  "type": "text",
                  "text": "hi"
              }
          ]
      }
```

其他模型的API格式如下：
```
      {
          "role": "user",
          "content": "hi"
      }
```

官方API所有模型均支持gpt-4-vision-preview格式的API。但你用的转发接口不支持gpt-4-vision-preview模型及其API格式。

所以你需要自行修改代码，只要把bot.py第83行注释掉就行了。

<img width="599" alt="image" src="https://github.com/yym68686/ChatGPT-Telegram-Bot/assets/31803242/5711eb5e-7370-4892-9b02-2c216a10eaab">
