### ISSUE TITLE
Bot does not reply on prompt, error in log

### ISSUE THREAD

**Issue by folis** [yym68686/ChatGPT-Telegram-Bot#64]
Hello,
Bot does not reply on prompt, while munu (/info) works fine.
Bot was redeployed several times with docker compose down and then up -d

Here is log:
2024-11-07 07:46:20,849 - root - WARNING - Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='xxxxx P.', id=9999, type=<ChatType.PRIVATE>, username='xxxxx'), date=datetime.datetime(2024, 11, 7, 7, 46, 20, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='xxxxx P.', id=9999, is_bot=False, is_premium=True, language_code='ru', username='xxxxx'), group_chat_created=False, message_id=395, supergroup_chat_created=False, text='Привет Хххх'), update_id=994689122)" caused error "'NoneType' object has
no attribute 'get_jobs_by_name'"
2024-11-07 07:46:20,852 - root - WARNING - Error traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/_application.py", line 1148, in __create_task_callback
    return await coroutine  # type: ignore[misc]
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
  File "/home/ChatGPT-Telegram-Bot/utils/decorators.py", line 103, in wrapper
    return await func(*args, **kwargs)
  File "/home/ChatGPT-Telegram-Bot/utils/decorators.py", line 43, in wrapper
    return await func(*args, **kwargs)
  File "/home/ChatGPT-Telegram-Bot/utils/decorators.py", line 34, in wrapper
    return await func(*args, **kwargs)
  File "/home/ChatGPT-Telegram-Bot/utils/decorators.py", line 93, in wrapper
    return await func(*args, **kwargs)
  File "/home/ChatGPT-Telegram-Bot/bot.py", line 108, in command_bot
    remove_job_if_exists(convo_id, context)
  File "/home/ChatGPT-Telegram-Bot/bot.py", line 622, in remove_job_if_exists
    current_jobs = context.job_queue.get_jobs_by_name(name)
AttributeError: 'NoneType' object has no attribute 'get_jobs_by_name'

Thank you for you help

**Comment by yym68686** [comment]
@folis update your docker image.
