### ISSUE TITLE
ChatGPT Telegram Bot stop working with my Environments.

### ISSUE THREAD

**Issue by chelaxian** [yym68686/ChatGPT-Telegram-Bot#71]
ChatGPT Telegram Bot stop working with my Environments.

When try to start manualy I get this errors
```bash
(venv) root@Nginx-Docker-TG:~/Telegram# cd ChatGPT-Telegram-Bot/
(venv) root@Nginx-Docker-TG:~/Telegram/ChatGPT-Telegram-Bot# source venv/bin/activate
(venv) root@Nginx-Docker-TG:~/Telegram/ChatGPT-Telegram-Bot# python3 bot.py 
Traceback (most recent call last):
  File "/root/Telegram/ChatGPT-Telegram-Bot/bot.py", line 6, in <module>
    import utils.decorators as decorators
  File "/root/Telegram/ChatGPT-Telegram-Bot/utils/decorators.py", line 1, in <module>
    import config
  File "/root/Telegram/ChatGPT-Telegram-Bot/config.py", line 337, in <module>
    InitEngine(chat_id=None)
  File "/root/Telegram/ChatGPT-Telegram-Bot/config.py", line 308, in InitEngine
    ChatGPTbot = chatgpt(temperature=temperature, print_log=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Telegram/ChatGPT-Telegram-Bot/ModelMerge/src/ModelMerge/models/chatgpt.py", line 66, in __init__
    super().__init__(api_key, engine, api_url, system_prompt, proxy, timeout, max_tokens, temperature, top_p, presence_penalty, frequency_penalty, reply_count, truncate_limit, use_plugins=use_plugins, print_log=print_log)
  File "/root/Telegram/ChatGPT-Telegram-Bot/ModelMerge/src/ModelMerge/models/base.py", line 110, in __init__
    self.aclient = httpx.AsyncClient(
                   ^^^^^^^^^^^^^^^^^^
TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxies'
(venv) root@Nginx-Docker-TG:~/Telegram/ChatGPT-Telegram-Bot# 
```

Before starting bot i setted up this Environment Variables:

```bash
export BOT_TOKEN="000000000:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
export API_URL="http://uni-api:8001/v1/chat/completions"
export API="sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
export GROQ_API_KEY="gsk_XXXXXXXXXXXXXXXXXXXX"
export GOOGLE_AI_API_KEY="XXXXXXXXXXXXXXXXXXXXXXXXX"
export VERTEX_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nXXXXXXXXXXXXXXXXXXXXX"
export VERTEX_PROJECT_ID="xxxxx-xxxxx-xxxxx-m8"
export VERTEX_CLIENT_EMAIL="vertex-ai@xxxxx-xxxxx-xxxxx-m8.iam.gserviceaccount.com"
export GET_MODELS="False"
export CUSTOM_MODELS="-all,gpt-o1,gpt-o1-mini,gpt-4o,gpt-4o-mini,gpt-4-turbo,gpt-4,gpt-3.5-turbo,lfm-40b,llama3,llama-3.1,llama-3.2,llama-3.2-vision,gemma,gemma-2,gemini-1.0-pro,gemini-1.5-flash,gemini-1.5-pro,qwen,mixtral,mythomist,openchat,toppy-m,zephyr,mythomax,claude-1,claude-1.3,claude-3-opus,claude-3-haiku,claude-3-sonnet,claude-3-5-sonnet,code-llama,dbrx,flux,google-palm,llava,playground-2.5,stable-diffusion-3"
export GPT_ENGINE="gpt-4o-mini"
export RESET_TIME="3600"
export CHAT_MODE="multiusers"
export TITLE="True"
export REPLY="True"
export LONG_TEXT="True"
export LONG_TEXT_SPLIT="True"
export FOLLOW_UP="False"
export FILE_UPLOAD_MESS="True"
export SEARCH="False"
export URL="False"
export ARXIV="False"
export CODE="False"
export IMAGE="False"
export DATE="False"
export PORT="8888"
export WEB_HOOK="https://xxxxxxxxxxxxxxx"
export GROUP_LIST="-100xxxxx,-100xxxxxxxxx"
export LANGUAGE="Russian"
```

when i use minimal Envoronment Setup like this
```bash
export BOT_TOKEN=000000000:XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
export API_URL=http://127.0.0.1:1337/v1/chat/completions
python -u bot.py
```
all works.

why bot was work before with my Environment Variables and now it stop working?

**Comment by chelaxian** [comment]
also it uses uni-api

**Comment by yym68686** [comment]
Hi, I may have fixed this issue. Try redeploying the bot.

**Comment by chelaxian** [comment]
> Hi, I may have fixed this issue. Try redeploying the bot.

yes. it works now. thanks!
