### ISSUE TITLE
请教一个报错

### ISSUE THREAD

**Issue by CCCAUCHY** [yym68686/ChatGPT-Telegram-Bot#72]
```
Traceback (most recent call last):
  File "/home/ec2-user/ChatGPT-Telegram-Bot/bot.py", line 6, in <module>
    import utils.decorators as decorators
  File "/home/ec2-user/ChatGPT-Telegram-Bot/utils/decorators.py", line 1, in <module>
    import config
  File "/home/ec2-user/ChatGPT-Telegram-Bot/config.py", line 9, in <module>
    from ModelMerge.src.ModelMerge.utils import prompt
  File "/home/ec2-user/ChatGPT-Telegram-Bot/ModelMerge/src/ModelMerge/__init__.py", line 1, in <module>
    from .models import *
  File "/home/ec2-user/ChatGPT-Telegram-Bot/ModelMerge/src/ModelMerge/models/__init__.py", line 7, in <module>
    from .duckduckgo import *
  File "/home/ec2-user/ChatGPT-Telegram-Bot/ModelMerge/src/ModelMerge/models/duckduckgo.py", line 113, in <module>
    class DuckChat:
  File "/home/ec2-user/ChatGPT-Telegram-Bot/ModelMerge/src/ModelMerge/models/duckduckgo.py", line 117, in DuckChat
    client: httpx.AsyncClient | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
在Amazon Linux上直接运行`python3 bot.py`

**Comment by yym68686** [comment]
应该是免费的duckduckgo服务不稳定，后面我尝试能不能修复。目前使用机器人请设置自己的 API key。

**Comment by CCCAUCHY** [comment]
> 应该是免费的duckduckgo服务不稳定，后面我尝试能不能修复。目前使用机器人请设置自己的 API key。

```
Traceback (most recent call last):
  File "/home/ec2-user/ChatGPT-Telegram-Bot/bot.py", line 6, in <module>
    import utils.decorators as decorators
  File "/home/ec2-user/ChatGPT-Telegram-Bot/utils/decorators.py", line 1, in <module>
    import config
  File "/home/ec2-user/ChatGPT-Telegram-Bot/config.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
```
没有openai的key, 用的是xAI, API_URL=https://api.x.ai/v1/chat/completions, 也添加了GROQ_API_KEY, 还是报这个错

**Comment by CCCAUCHY** [comment]
> 应该是免费的duckduckgo服务不稳定，后面我尝试能不能修复。目前使用机器人请设置自己的 API key。

只`export BOT_TOKEN`也不行, 报错:
```
Traceback (most recent call last):
  File "/home/ec2-user/ChatGPT-Telegram-Bot/bot.py", line 6, in <module>
    import utils.decorators as decorators
  File "/home/ec2-user/ChatGPT-Telegram-Bot/utils/decorators.py", line 1, in <module>
    import config
  File "/home/ec2-user/ChatGPT-Telegram-Bot/config.py", line 9, in <module>
    from ModelMerge.src.ModelMerge.utils import prompt
  File "/home/ec2-user/ChatGPT-Telegram-Bot/ModelMerge/src/ModelMerge/__init__.py", line 1, in <module>
    from .models import *
  File "/home/ec2-user/ChatGPT-Telegram-Bot/ModelMerge/src/ModelMerge/models/__init__.py", line 7, in <module>
    from .duckduckgo import *
  File "/home/ec2-user/ChatGPT-Telegram-Bot/ModelMerge/src/ModelMerge/models/duckduckgo.py", line 113, in <module>
    class DuckChat:
  File "/home/ec2-user/ChatGPT-Telegram-Bot/ModelMerge/src/ModelMerge/models/duckduckgo.py", line 117, in DuckChat
    client: httpx.AsyncClient | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by yym68686** [comment]
> > 应该是免费的duckduckgo服务不稳定，后面我尝试能不能修复。目前使用机器人请设置自己的 API key。
> 
> ```
> Traceback (most recent call last):
>   File "/home/ec2-user/ChatGPT-Telegram-Bot/bot.py", line 6, in <module>
>     import utils.decorators as decorators
>   File "/home/ec2-user/ChatGPT-Telegram-Bot/utils/decorators.py", line 1, in <module>
>     import config
>   File "/home/ec2-user/ChatGPT-Telegram-Bot/config.py", line 3, in <module>
>     from dotenv import load_dotenv
> ModuleNotFoundError: No module named 'dotenv'
> ```
> 
> 没有openai的key, 用的是xAI, API_URL=https://api.x.ai/v1/chat/completions, 也添加了GROQ_API_KEY, 还是报这个错

这个是因为你没有按照 README 提示执行 pip install -r requirements.txt 导致的。建议使用 docker 运行，你的问题都是环境问题导致的。

**Comment by CCCAUCHY** [comment]
> > > 应该是免费的duckduckgo服务不稳定，后面我尝试能不能修复。目前使用机器人请设置自己的 API key。
> > 
> > 
> > ```
> > Traceback (most recent call last):
> >   File "/home/ec2-user/ChatGPT-Telegram-Bot/bot.py", line 6, in <module>
> >     import utils.decorators as decorators
> >   File "/home/ec2-user/ChatGPT-Telegram-Bot/utils/decorators.py", line 1, in <module>
> >     import config
> >   File "/home/ec2-user/ChatGPT-Telegram-Bot/config.py", line 3, in <module>
> >     from dotenv import load_dotenv
> > ModuleNotFoundError: No module named 'dotenv'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 没有openai的key, 用的是xAI, API_URL=https://api.x.ai/v1/chat/completions, 也添加了GROQ_API_KEY, 还是报这个错
> 
> 这个是因为你没有按照 README 提示执行 pip install -r requirements.txt 导致的。建议使用 docker 运行，你的问题都是环境问题导致的。

执行了的
```
[ec2-user@ip-172-26-0-188 ChatGPT-Telegram-Bot]$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.python.org/simple/
Requirement already satisfied: python-dotenv in /home/ec2-user/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (1.0.1)
Requirement already satisfied: python-telegram-bot[job-queue,rate-limiter,webhooks]==21.0.1 in /home/ec2-user/.local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (21.0.1)
Requirement already satisfied: pytz in /usr/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (2022.7.1)
Requirement already satisfied: msgspec in /home/ec2-user/.local/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (0.18.6)
Requirement already satisfied: PyExecJS in /home/ec2-user/.local/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (1.5.1)
Requirement already satisfied: requests in /home/ec2-user/.local/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (2.32.3)
Requirement already satisfied: html2text in /home/ec2-user/.local/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (2024.2.26)
Requirement already satisfied: fake-useragent in /home/ec2-user/.local/lib/python3.9/site-packages (from -r requirements.txt (line 10)) (2.0.3)
Requirement already satisfied: beautifulsoup4 in /home/ec2-user/.local/lib/python3.9/site-packages (from -r requirements.txt (line 11)) (4.12.3)
Requirement already satisfied: tiktoken==0.6.0 in /home/ec2-user/.local/lib/python3.9/site-packages (from -r requirements.txt (line 12)) (0.6.0)
Requirement already satisfied: lxml-html-clean in /home/ec2-user/.local/lib/python3.9/site-packages (from -r requirements.txt (line 13)) (0.4.1)
Requirement already satisfied: pdfminer.six==20231228 in /home/ec2-user/.local/lib/python3.9/site-packages (from -r requirements.txt (line 14)) (20231228)
Requirement already satisfied: duckduckgo-search==5.3.1 in /home/ec2-user/.local/lib/python3.9/site-packages (from -r requirements.txt (line 15)) (5.3.1)
Requirement already satisfied: httpx~=0.27 in /home/ec2-user/.local/lib/python3.9/site-packages (from python-telegram-bot[job-queue,rate-limiter,webhooks]==21.0.1->-r requirements.txt (line 3)) (0.28.1)
Requirement already satisfied: APScheduler~=3.10.4 in /home/ec2-user/.local/lib/python3.9/site-packages (from python-telegram-bot[job-queue,rate-limiter,webhooks]==21.0.1->-r requirements.txt (line 3)) (3.10.4)
Requirement already satisfied: aiolimiter~=1.1.0 in /home/ec2-user/.local/lib/python3.9/site-packages (from python-telegram-bot[job-queue,rate-limiter,webhooks]==21.0.1->-r requirements.txt (line 3)) (1.1.1)
Requirement already satisfied: tornado~=6.4 in /home/ec2-user/.local/lib/python3.9/site-packages (from python-telegram-bot[job-queue,rate-limiter,webhooks]==21.0.1->-r requirements.txt (line 3)) (6.4.2)
Requirement already satisfied: regex>=2022.1.18 in /home/ec2-user/.local/lib/python3.9/site-packages (from tiktoken==0.6.0->-r requirements.txt (line 12)) (2024.11.6)
Requirement already satisfied: charset-normalizer>=2.0.0 in /home/ec2-user/.local/lib/python3.9/site-packages (from pdfminer.six==20231228->-r requirements.txt (line 14)) (3.4.0)
Requirement already satisfied: cryptography>=36.0.0 in /usr/lib64/python3.9/site-packages (from pdfminer.six==20231228->-r requirements.txt (line 14)) (36.0.1)
Requirement already satisfied: curl-cffi>=0.7.0b4 in /home/ec2-user/.local/lib/python3.9/site-packages (from duckduckgo-search==5.3.1->-r requirements.txt (line 15)) (0.8.0b7)
Requirement already satisfied: click>=8.1.7 in /home/ec2-user/.local/lib/python3.9/site-packages (from duckduckgo-search==5.3.1->-r requirements.txt (line 15)) (8.1.7)
Requirement already satisfied: orjson>=3.10.3 in /home/ec2-user/.local/lib/python3.9/site-packages (from duckduckgo-search==5.3.1->-r requirements.txt (line 15)) (3.10.12)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3.9/site-packages (from PyExecJS->-r requirements.txt (line 7)) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/.local/lib/python3.9/site-packages (from requests->-r requirements.txt (line 8)) (2024.8.30)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.9/site-packages (from requests->-r requirements.txt (line 8)) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3.9/site-packages (from requests->-r requirements.txt (line 8)) (1.25.10)
Requirement already satisfied: importlib-resources>=6.0 in /home/ec2-user/.local/lib/python3.9/site-packages (from fake-useragent->-r requirements.txt (line 10)) (6.4.5)
Requirement already satisfied: soupsieve>1.2 in /home/ec2-user/.local/lib/python3.9/site-packages (from beautifulsoup4->-r requirements.txt (line 11)) (2.6)
Requirement already satisfied: lxml in /home/ec2-user/.local/lib/python3.9/site-packages (from lxml-html-clean->-r requirements.txt (line 13)) (5.3.0)
Requirement already satisfied: tzlocal!=3.*,>=2.0 in /home/ec2-user/.local/lib/python3.9/site-packages (from APScheduler~=3.10.4->python-telegram-bot[job-queue,rate-limiter,webhooks]==21.0.1->-r requirements.txt (line 3)) (5.2)
Requirement already satisfied: cffi>=1.12 in /usr/lib64/python3.9/site-packages (from cryptography>=36.0.0->pdfminer.six==20231228->-r requirements.txt (line 14)) (1.14.5)
Requirement already satisfied: httpcore==1.* in /home/ec2-user/.local/lib/python3.9/site-packages (from httpx~=0.27->python-telegram-bot[job-queue,rate-limiter,webhooks]==21.0.1->-r requirements.txt (line 3)) (1.0.7)
Requirement already satisfied: anyio in /home/ec2-user/.local/lib/python3.9/site-packages (from httpx~=0.27->python-telegram-bot[job-queue,rate-limiter,webhooks]==21.0.1->-r requirements.txt (line 3)) (4.7.0)
Requirement already satisfied: h11<0.15,>=0.13 in /home/ec2-user/.local/lib/python3.9/site-packages (from httpcore==1.*->httpx~=0.27->python-telegram-bot[job-queue,rate-limiter,webhooks]==21.0.1->-r requirements.txt (line 3)) (0.14.0)
Requirement already satisfied: zipp>=3.1.0 in /home/ec2-user/.local/lib/python3.9/site-packages (from importlib-resources>=6.0->fake-useragent->-r requirements.txt (line 10)) (3.21.0)
Requirement already satisfied: pycparser in /usr/lib/python3.9/site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20231228->-r requirements.txt (line 14)) (2.20)
Requirement already satisfied: typing_extensions>=4.5 in /home/ec2-user/.local/lib/python3.9/site-packages (from anyio->httpx~=0.27->python-telegram-bot[job-queue,rate-limiter,webhooks]==21.0.1->-r requirements.txt (line 3)) (4.12.2)
Requirement already satisfied: sniffio>=1.1 in /home/ec2-user/.local/lib/python3.9/site-packages (from anyio->httpx~=0.27->python-telegram-bot[job-queue,rate-limiter,webhooks]==21.0.1->-r requirements.txt (line 3)) (1.3.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in /home/ec2-user/.local/lib/python3.9/site-packages (from anyio->httpx~=0.27->python-telegram-bot[job-queue,rate-limiter,webhooks]==21.0.1->-r requirements.txt (line 3)) (1.2.2)
Requirement already satisfied: ply==3.11 in /usr/lib/python3.9/site-packages (from pycparser->cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20231228->-r requirements.txt (line 14)) (3.11)
[ec2-user@ip-172-26-0-188 ChatGPT-Telegram-Bot]$ python3.12 bot.py
Traceback (most recent call last):
  File "/home/ec2-user/ChatGPT-Telegram-Bot/bot.py", line 6, in <module>
    import utils.decorators as decorators
  File "/home/ec2-user/ChatGPT-Telegram-Bot/utils/decorators.py", line 1, in <module>
    import config
  File "/home/ec2-user/ChatGPT-Telegram-Bot/config.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
```

**Comment by yym68686** [comment]
建议使用 docker 部署本项目。裸环境你可能整不明白。

**Comment by yym68686** [comment]
你好，如果没有额外的信息提供。本 issue 将被视为已解决，将在一天后关闭。
